### ISSUE TITLE
Move date typecasts into stg models

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/dbt-synthea#40]
There are repeated typecasts of timestamp-->date in the OMOP models.  To DRY up the code we can move these into the original stg models by creating a _date column in those models and carrying it through to the final models.

For example: https://github.com/OHDSI/dbt-synthea/blob/236f52ab1f651e418eab6978d6a9bb92754ad682/models/omop/drug_exposure.sql#L11

**Comment by katy-sadowski** [comment]
@lawrenceadams , I have addressed this Issue in commit https://github.com/OHDSI/dbt-synthea/commit/ae791145d50c9e0693880ff9ed37d60f7cc0195d 

I accidentally pushed to main 🙈 I had branch protections relaxed for myself in the early days and forgot I was working on main. I have added these back now so I won't be able to do that in the future...oopsie!  It runs and passes all tests on duckdb and Postgres.  If you'd like to take a look / test the changes please do!  What I did:

- Moved casts upstream where applicable to reduce repetition
- Changed all casts to use dbt.cast 
- Spotted a couple other opportunities to use dbt macros (datediff, dateadd)
- Renamed some columns to indicate that they're datetimes, not dates (holdover from ETL-Synthea)

**Comment by lawrenceadams** [comment]
Oops! easily done (have done it myself before)!!

Excellent commit! 💪
