### ISSUE TITLE
Investigate dbt test failure

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/dbt-synthea#50]
We have 1 failing test on the seed dataset:

23:51:46  Completed with 1 error and 0 warnings:
23:51:46  
23:51:46  Failure in test relationships_stg_synthea__claims_transactions_patient_insurance_id__member_id__ref_stg_synthea__payer_transitions_ (models/staging/synthea/_synthea__models.yml)
23:51:46    Got 4598 results, configured to fail if != 0

The issue seems to be a data issue in Synthea (I had marked member_id as an FK due to the note here: https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary#claims-transactions).  We should investigate further.

**Comment by lawrenceadams** [comment]
Doing some digging, it looks like the table `ClaimTransition.memberId` is [defined here](https://github.com/synthetichealth/synthea/blob/76f2925bbcb098c34413b4c1e245d8664d7251d7/src/main/java/org/mitre/synthea/export/CSVExporter.java#L1833C23-L1833C50), which in term returns the `id` [here](https://github.com/synthetichealth/synthea/blob/76f2925bbcb098c34413b4c1e245d8664d7251d7/src/main/java/org/mitre/synthea/world/concepts/Claim.java#L343-L345).

Following the trail leads us [here](https://github.com/synthetichealth/synthea/blob/76f2925bbcb098c34413b4c1e245d8664d7251d7/src/main/java/org/mitre/synthea/export/CSVExporter.java#L1952-L1955) - the documentation is very vague / plain incorrect, the CSV will yield the patient ID _if_ they have a membership from [here](https://github.com/synthetichealth/synthea/blob/76f2925bbcb098c34413b4c1e245d8664d7251d7/src/main/java/org/mitre/synthea/world/concepts/Claim.java#L343-L345)

**Comment by lawrenceadams** [comment]
https://github.com/synthetichealth/synthea/issues/1508 issue raised.
