### ISSUE TITLE
Create empty source_to_concept_map model instead of seeding it

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/dbt-synthea#95]
Right now, the seed vocab includes an empty STCM table, and BYO data mode has no handling of this table (other than an assumption the user will bring their own empty table).  This can cause an error in BYO mode in Postgres if the user didn't load this table.

Since we're not using the table in this project yet, for now we should just create an empty one as an omop model and remove the empty seed and stg model.

**Comment by lawrenceadams** [comment]
Had the same problem in snowflake - good catch!
